#ifndef PROJECT_DEFINES_H
#define PROJECT_DEFINES_H

//#define SIMULATION_MODE

#define EX_ARDUINOHA_CAMERA
#define EX_ARDUINOHA_COVER
#define EX_ARDUINOHA_DEVICE_TRACKER
#define EX_ARDUINOHA_DEVICE_TRIGGER
#define EX_ARDUINOHA_FAN
#define EX_ARDUINOHA_HVAC
#define EX_ARDUINOHA_LOCK
#define EX_ARDUINOHA_SCENE
#define EX_ARDUINOHA_TAG_SCANNER

#endif // PROJECT_DEFINES_H
